config/routes.rb
Rails.application.routes.draw do
  get root to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  post 'tasks/new', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'show'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  post 'tasks/update', to: 'tasks#update', as: 'update_task'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # byebug
    @task = Task.new(task_params)
    @task.save

    redirect_to root_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to show_path(params[:id])
  end

  def destroy
    byebug
  end

  private

  # STRONG PARAMS
  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="display-1">Edit '<%= @task.title  %>' task</h1>
<div class="form-group">
  <form action="/tasks/update" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag :id, @task[:id] %>
    <label for="title">Title</label>
    <input type="text" name="task[title]" id="title" class="form-control">
    <label for="details">Details</label>
    <input type="text" name="task[details]" id="details" class="form-control">
    <input type="submit" class="btn btn-primary my-3">
  </form>

</div>

app/views/tasks/index.html.erb
<h1 class="display-1">My Tasks</h1>

<% @tasks.each do |task| %>
<div class="form-check">
  <input type="checkbox" class="form-check-input" id=<%= "default-check#{task.id}"  %> <%= task.completed ? "checked" : ""%>>
  <label class="form-check-label" for=<%= "default-check#{task.id}"%>><%= link_to task.title, show_path(task["id"]) %></label><%= link_to "Delete", destroy_task_path(task[:id]) %>
</div>
<% end %>
<hr>
<p><%= link_to "Add a new task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1 class="display-1">Add a new task</h1>
<div class="form-group">
  <form action="/tasks/new" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <label for="title">Title</label>
    <input type="text" name="task[title]" id="title" class="form-control">
    <label for="details">Details</label>
    <input type="text" name="task[details]" id="details" class="form-control">
    <input type="submit" class="btn btn-primary my-3">
  </form>

</div>

app/views/tasks/show.html.erb
<h2 class="display-1"><%= @task.title %></h1>
  <hr>
<%= link_to "Edit", edit_task_path(@task) %>
<hr>

<p class="lead"><%= @task.details  %></p>

<div class="form-check">
  <input type="checkbox" class="form-check-input" id=<%= "default-check#{@task.id}"  %> <%= @task.completed ? "checked" : ""%>>
  <label class="form-check-label" for=<%= "default-check#{@task.id}"%>><%= @task.title %></label>
</div>
<hr>

<%= link_to "Go back", root_path %>